version: '3.1'

services:
  db:
    image: mysql:8
    container_name: mysql-agromarket
    restart: always
    environment:
      MYSQL_DATABASE: agromarketplace
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: 