# Generated by Django 5.1.7 on 2025-04-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='documento_cnh',
            field=models.ImageField(upload_to='documentos/cnh/', verbose_name='Documento CNH'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='documento_rg',
            field=models.ImageField(upload_to='documentos/rg/', verbose_name='Documento RG'),
        ),
    ]
