# Generated by Django 5.1.7 on 2025-04-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_documento_cnh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='documento_cnh',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='documento_rg',
        ),
        migrations.AddField(
            model_name='usuario',
            name='documento',
            field=models.ImageField(blank=True, null=True, upload_to='documentos/', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do Documento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='orgao_emissor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Órgão Emissor'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('RG', 'RG'), ('CNH', 'CNH')], max_length=3, null=True, verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='uf_documento',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='UF do Documento'),
        ),
    ]
