# Generated by Django 5.1.7 on 2025-04-03 15:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('em_preparacao', 'Em Preparação'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Unitário')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Quilograma (kg)'), ('g', 'Grama (g)'), ('l', 'Litro (L)'), ('ml', 'Mililitro (mL)'), ('un', 'Unidade (un)')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('product_type', models.CharField(choices=[('feijao', 'Feijão'), ('algodao', 'Algodão'), ('gergelim', 'Gergelim'), ('pastagem', 'Pastagem'), ('milho', 'Milho'), ('soja', 'Soja')], max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('lot', models.CharField(blank=True, max_length=50, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('minimum_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('packaging', models.CharField(blank=True, choices=[('bag', 'Saco'), ('box', 'Caixa'), ('bottle', 'Garrafa'), ('can', 'Lata'), ('other', 'Outro')], max_length=20, null=True)),
                ('sieve', models.CharField(blank=True, max_length=50, null=True)),
                ('variety', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(choices=[('BRL', 'Real (R$)'), ('USD', 'Dólar ($)'), ('EUR', 'Euro (€)')], default='BRL', max_length=3)),
                ('allow_exchange', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.product_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('rg', 'RG'), ('cnh', 'CNH')], max_length=3)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('documento', models.FileField(upload_to='documentos/')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cadastro de Vendedor',
                'verbose_name_plural': 'Cadastros de Vendedores',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='VendorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Aplicação de Vendedor',
                'verbose_name_plural': 'Aplicações de Vendedores',
                'ordering': ['-created_at'],
            },
        ),
    ]
