# Generated by Django 5.1.7 on 2025-05-14 18:11

import core.models
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('respondido', models.BooleanField(default=False)),
                ('resposta', models.TextField(blank=True, null=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('encerrado', models.BooleanField(default=False)),
                ('data_encerramento', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mensagem de Suporte',
                'verbose_name_plural': 'Mensagens de Suporte',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='MensagemSuporteThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_propriedade', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18)),
                ('hectares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cultivo_principal', models.CharField(choices=[('feijao', 'Feijão'), ('algodao', 'Algodão'), ('gergelim', 'Gergelim'), ('pastagem', 'Pastagem'), ('milho', 'Milho'), ('soja', 'Soja')], max_length=20)),
                ('estado', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=9)),
                ('referencia', models.CharField(blank=True, max_length=200, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], default='PENDENTE', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('tipo_venda', models.CharField(choices=[('avista', 'À Vista'), ('prazo', 'A Prazo')], default='avista', max_length=10)),
                ('documento_ir', models.FileField(blank=True, null=True, upload_to='documentos/ir/')),
                ('inscricao_estadual', models.FileField(blank=True, null=True, upload_to='documentos/inscricao_estadual/')),
                ('documento_matricula', models.FileField(blank=True, null=True, upload_to='documentos/matricula/')),
                ('is_arrendatario', models.BooleanField(default=False)),
                ('documento_arrendamento', models.FileField(blank=True, null=True, upload_to='documentos/arrendamento/')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('justificativa_reprovacao', models.TextField(blank=True, null=True)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('reprovado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('available_volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Volume Disponível')),
                ('unit', models.CharField(choices=[('kg', 'Quilograma (kg)'), ('l', 'Litro (L)'), ('un', 'Unidade (un)')], max_length=2, verbose_name='Unidade')),
                ('product_type', models.CharField(choices=[('feijao', 'Feijão'), ('algodao', 'Algodão'), ('gergelim', 'Gergelim'), ('pastagem', 'Pastagem'), ('milho', 'Milho'), ('soja', 'Soja')], max_length=20, verbose_name='Tipo de Produto')),
                ('packaging', models.CharField(default='Saco', max_length=50, verbose_name='Embalagem')),
                ('currency', models.CharField(choices=[('BRL', 'Real (R$)'), ('USD', 'Dólar ($)'), ('EUR', 'Euro (€)')], default='BRL', max_length=3, verbose_name='Moeda')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.product_image_path, verbose_name='Imagem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fabricante')),
                ('lot', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('minimum_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantidade Mínima')),
                ('sieve', models.CharField(blank=True, max_length=50, null=True, verbose_name='Peneira')),
                ('variety', models.CharField(blank=True, max_length=100, null=True, verbose_name='Variedade')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='SellerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('sobrenome', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('tipo_documento', models.CharField(blank=True, choices=[('RG', 'RG'), ('CNH', 'CNH')], max_length=3, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('hectares_atendidos', models.IntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MinValueValidator(10)])),
                ('culturas_atendidas', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cadastro de Vendedor',
                'verbose_name_plural': 'Cadastros de Vendedores',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('categoria_sugerida', models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoria Sugerida')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Volume')),
                ('unidade_medida', models.CharField(blank=True, choices=[('ton', 'Tonelada'), ('kg', 'Quilograma'), ('l', 'Litro'), ('un', 'Unidade'), ('cx', 'Caixa'), ('sc', 'Saco')], max_length=3, null=True, verbose_name='Unidade de Medida')),
                ('fabricante', models.CharField(blank=True, default='Não especificado', max_length=100, null=True, verbose_name='Fabricante')),
                ('tipo_produto', models.CharField(blank=True, choices=[('ins', 'Insumo'), ('sem', 'Semente'), ('def', 'Defensivo'), ('fer', 'Fertilizante'), ('equ', 'Equipamento'), ('out', 'Outro')], max_length=3, null=True, verbose_name='Tipo de Produto')),
                ('lote', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote')),
                ('peneira', models.CharField(blank=True, max_length=50, null=True, verbose_name='Peneira')),
                ('variedade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Variedade')),
                ('embalagem', models.CharField(blank=True, choices=[('big', 'Big Bag'), ('sac', 'Saco'), ('cax', 'Caixa'), ('gal', 'Galão'), ('bom', 'Bombona'), ('con', 'Container'), ('out', 'Outro')], max_length=3, null=True, verbose_name='Embalagem')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações Adicionais')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20, verbose_name='Status')),
                ('resposta_superadmin', models.TextField(blank=True, null=True, verbose_name='Resposta do Administrador')),
            ],
            options={
                'verbose_name': 'Solicitação de Produto',
                'verbose_name_plural': 'Solicitações de Produtos',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('sobrenome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sobrenome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('tipo_documento', models.CharField(blank=True, choices=[('RG', 'RG'), ('CNH', 'CNH')], max_length=3, null=True, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do Documento')),
                ('arquivo_documento', models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Arquivo do Documento')),
                ('hectares_atendidos', models.IntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Quantidade de Hectares Atendidos')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('ENTREGUE', 'Entregue')], default='PENDENTE', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='VendorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=200)),
                ('cnpj', models.CharField(default='00000000000000', max_length=14, unique=True)),
                ('address', models.TextField(default='')),
                ('phone', models.CharField(default='', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='vendor_documents/')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
            ],
        ),
    ]
