# Generated by Django 5.1.7 on 2025-04-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='inscricao_estadual',
            field=models.FileField(blank=True, null=True, upload_to='documentos/inscricao_estadual/'),
        ),
    ]
