# Generated by Django 5.1.7 on 2025-04-29 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pedido_inscricao_estadual'),
        ('core', '0002_initial'),
    ]

    operations = [
    ]
