# Generated by Django 5.2 on 2025-04-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mensagemsuportethread'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemsuporte',
            name='data_encerramento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensagemsuporte',
            name='encerrado',
            field=models.BooleanField(default=False),
        ),
    ]
