# Generated by Django 5.1.7 on 2025-04-04 17:24

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_productimage'),
        ('vendedor', '0005_remove_vendedor_bairro_remove_vendedor_cpf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='allow_exchange',
            field=models.BooleanField(default=False, verbose_name='Permite Troca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_volume',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Volume Disponível'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('BRL', 'Real (R$)'), ('USD', 'Dólar ($)'), ('EUR', 'Euro (€)')], default='BRL', max_length=3, verbose_name='Moeda'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validade'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.product_image_path, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lot',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantidade Mínima'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='product',
            name='packaging',
            field=models.CharField(blank=True, choices=[('bag', 'Saco'), ('box', 'Caixa'), ('bottle', 'Garrafa'), ('can', 'Lata'), ('other', 'Outro')], max_length=20, null=True, verbose_name='Embalagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('feijao', 'Feijão'), ('algodao', 'Algodão'), ('gergelim', 'Gergelim'), ('pastagem', 'Pastagem'), ('milho', 'Milho'), ('soja', 'Soja')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendedor.vendedor', verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sieve',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Peneira'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Quilograma (kg)'), ('g', 'Grama (g)'), ('l', 'Litro (L)'), ('ml', 'Mililitro (mL)'), ('un', 'Unidade (un)')], max_length=10, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variety',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Variedade'),
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('em_preparacao', 'Em Preparação'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.order')),
            ],
            options={
                'verbose_name': 'Histórico de Pedido',
                'verbose_name_plural': 'Históricos de Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ConsultaIA',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
