# Generated by Django 5.1.7 on 2025-04-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Histórico de Pedido', 'verbose_name_plural': 'Histórico de Pedidos'},
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
