# Generated by Django 5.1.7 on 2025-04-05 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_mensagemsuporte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100)),
                ('categoria_sugerida', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('volume', models.CharField(blank=True, max_length=50, null=True)),
                ('unidade', models.CharField(blank=True, max_length=50, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ANALISADO', 'Analisado')], default='PENDENTE', max_length=20)),
                ('resposta_superadmin', models.TextField(blank=True, null=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_produtos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Produto',
                'verbose_name_plural': 'Solicitações de Produtos',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
