# Generated by Django 5.1.7 on 2025-04-05 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_solicitacaoproduto'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagemsuporte',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_suporte', to='usuarios.usuario'),
        ),
    ]
