# Generated by Django 5.1.7 on 2025-04-05 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_mensagemsuporte_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='solicitacaoproduto',
            options={'verbose_name': 'Solicitação de Produto', 'verbose_name_plural': 'Solicitações de Produtos'},
        ),
        migrations.AlterModelOptions(
            name='vendorapplication',
            options={},
        ),
        migrations.RemoveField(
            model_name='solicitacaoproduto',
            name='fabricante',
        ),
        migrations.RemoveField(
            model_name='solicitacaoproduto',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='solicitacaoproduto',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='vendorapplication',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='solicitacaoproduto',
            name='data_analise',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoproduto',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='solicitacaoproduto',
            name='unidade_medida',
            field=models.CharField(choices=[('kg', 'Quilograma'), ('g', 'Grama'), ('l', 'Litro'), ('ml', 'Mililitro'), ('un', 'Unidade')], default='un', max_length=2),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='cnpj',
            field=models.CharField(default='00000000000000', max_length=14, unique=True),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='company_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='vendor_documents/'),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='mensagemsuporte',
            name='assunto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mensagemsuporte',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='nome_produto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=10),
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_produto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendorapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
