# Generated by Django 5.1.7 on 2025-04-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoproduto',
            name='data_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoproduto',
            name='embalagem',
            field=models.CharField(blank=True, choices=[('bag', 'Saco'), ('box', 'Caixa'), ('bottle', 'Garrafa'), ('can', 'Lata'), ('other', 'Outro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoproduto',
            name='fabricante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoproduto',
            name='lote',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoproduto',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoproduto',
            name='peneira',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoproduto',
            name='tipo_produto',
            field=models.CharField(blank=True, choices=[('feijao', 'Feijão'), ('algodao', 'Algodão'), ('gergelim', 'Gergelim'), ('pastagem', 'Pastagem'), ('milho', 'Milho'), ('soja', 'Soja')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoproduto',
            name='variedade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
