# Generated by Django 5.1.7 on 2025-04-07 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_solicitacaoproduto_data_validade_and_more'),
    ]

    operations = [
    ]
