# Generated by Django 5.1.7 on 2025-04-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20250406_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='unidade_medida',
            field=models.CharField(choices=[('kg', 'Quilograma'), ('g', 'Grama'), ('l', 'Litro'), ('ml', 'Mililitro'), ('un', 'Unidade'), ('ton', 'Tonelada'), ('sc', 'Saca')], default='un', max_length=3),
        ),
    ]
