# Generated by Django 5.1.7 on 2025-04-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_solicitacaoproduto_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacaoproduto',
            options={'ordering': ['-data_solicitacao'], 'verbose_name': 'Solicitação de Produto', 'verbose_name_plural': 'Solicitações de Produtos'},
        ),
        migrations.RemoveField(
            model_name='solicitacaoproduto',
            name='data_analise',
        ),
        migrations.RemoveField(
            model_name='solicitacaoproduto',
            name='resposta_superadmin',
        ),
        migrations.RemoveField(
            model_name='solicitacaoproduto',
            name='vendedor',
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='categoria_sugerida',
            field=models.CharField(max_length=50, verbose_name='Categoria Sugerida'),
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação'),
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='data_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validade'),
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='embalagem',
            field=models.CharField(blank=True, choices=[('big', 'Big Bag'), ('sac', 'Saco'), ('cax', 'Caixa'), ('gal', 'Galão'), ('bom', 'Bombona'), ('con', 'Container'), ('out', 'Outro')], max_length=3, null=True, verbose_name='Embalagem'),
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='fabricante',
            field=models.CharField(default='Não especificado', max_length=100, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='lote',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='nome_produto',
            field=models.CharField(max_length=100, verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Adicionais'),
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='peneira',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Peneira'),
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='tipo_produto',
            field=models.CharField(blank=True, choices=[('ins', 'Insumo'), ('sem', 'Semente'), ('def', 'Defensivo'), ('fer', 'Fertilizante'), ('equ', 'Equipamento'), ('out', 'Outro')], max_length=3, null=True, verbose_name='Tipo de Produto'),
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='unidade_medida',
            field=models.CharField(choices=[('ton', 'Tonelada'), ('kg', 'Quilograma'), ('g', 'Grama'), ('l', 'Litro'), ('ml', 'Mililitro'), ('un', 'Unidade'), ('cx', 'Caixa'), ('sc', 'Saco')], max_length=3, verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='variedade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Variedade'),
        ),
    ]
