# Generated by Django 5.1.7 on 2025-04-07 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_solicitacaoproduto_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoproduto',
            name='resposta_superadmin',
            field=models.TextField(blank=True, null=True, verbose_name='Resposta do Administrador'),
        ),
        migrations.AddField(
            model_name='solicitacaoproduto',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
    ]
