# Generated by Django 5.1.7 on 2025-04-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_solicitacaoproduto_resposta_superadmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='categoria_sugerida',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoria Sugerida'),
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='fabricante',
            field=models.CharField(blank=True, default='Não especificado', max_length=100, null=True, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='nome_produto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='unidade_medida',
            field=models.CharField(blank=True, choices=[('ton', 'Tonelada'), ('kg', 'Quilograma'), ('g', 'Grama'), ('l', 'Litro'), ('ml', 'Mililitro'), ('un', 'Unidade'), ('cx', 'Caixa'), ('sc', 'Saco')], max_length=3, null=True, verbose_name='Unidade de Medida'),
        ),
    ]
