# Generated by Django 5.1.7 on 2025-04-07 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_solicitacaoproduto_categoria_sugerida_and_more'),
        ('vendedor', '0010_auto_20250406_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_propriedade', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18)),
                ('hectares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cultivo_principal', models.CharField(choices=[('soja', 'Soja'), ('milho', 'Milho'), ('cafe', 'Café'), ('cana', 'Cana-de-açúcar'), ('algodao', 'Algodão'), ('outros', 'Outros')], max_length=20)),
                ('estado', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=9)),
                ('referencia', models.CharField(blank=True, max_length=200, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PROCESSANDO', 'Processando'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('ENTREGUE', 'Entregue')], default='PROCESSANDO', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='core.usuario')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('ENTREGUE', 'Entregue')], default='PENDENTE', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='core.usuario')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='core.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='core.product')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='vendedor.vendedor')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
