# Generated by Django 5.1.7 on 2025-04-13 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_pedido_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='allow_exchange',
        ),
        migrations.AddField(
            model_name='pedido',
            name='documento_arrendamento',
            field=models.FileField(blank=True, null=True, upload_to='documentos/arrendamento/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='documento_ir',
            field=models.FileField(blank=True, null=True, upload_to='documentos/ir/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='documento_matricula',
            field=models.FileField(blank=True, null=True, upload_to='documentos/matricula/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='is_arrendatario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_venda',
            field=models.CharField(choices=[('avista', 'À Vista'), ('prazo', 'A Prazo')], default='avista', max_length=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cultivo_principal',
            field=models.CharField(choices=[('feijao', 'Feijão'), ('algodao', 'Algodão'), ('gergelim', 'Gergelim'), ('pastagem', 'Pastagem'), ('milho', 'Milho'), ('soja', 'Soja')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Quilograma (kg)'), ('l', 'Litro (L)'), ('un', 'Unidade (un)')], max_length=10, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='unidade_medida',
            field=models.CharField(blank=True, choices=[('ton', 'Tonelada'), ('kg', 'Quilograma'), ('l', 'Litro'), ('un', 'Unidade'), ('cx', 'Caixa'), ('sc', 'Saco')], max_length=3, null=True, verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='hectares_atendidos',
            field=models.IntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(300)], verbose_name='Quantidade de Hectares Atendidos'),
        ),
    ]
