# Generated by Django 5.1.7 on 2025-04-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_product_allow_exchange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packaging',
            field=models.CharField(default='Saco', max_length=50, verbose_name='Embalagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('feijao', 'Feijão'), ('algodao', 'Algodão'), ('gergelim', 'Gergelim'), ('pastagem', 'Pastagem'), ('milho', 'Milho'), ('soja', 'Soja')], max_length=20, verbose_name='Tipo de Produto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Quilograma (kg)'), ('l', 'Litro (L)'), ('un', 'Unidade (un)')], max_length=2, verbose_name='Unidade'),
        ),
    ]
