# Generated by Django 5.1.7 on 2025-04-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_pedido_total_alter_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
