# Generated by Django 5.1.7 on 2025-04-21 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_pedido_comprador_alter_pedido_vendedor'),
        ('produtos', '0009_alter_produto_embalagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto'),
        ),
    ]
