# Generated by Django 5.1.7 on 2025-04-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_itempedido_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_APROVACAO', 'Aguardando Aprovação'), ('APROVADO', 'Aprovado'), ('CANCELADO', 'Cancelado'), ('ENTREGUE', 'Entregue'), ('ARQUIVADO', 'Arquivado')], default='AGUARDANDO_APROVACAO', max_length=20),
        ),
    ]
