# Generated by Django 5.2 on 2025-04-26 01:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_venda_comprador_alter_venda_vendedor_carrinho_and_more'),
        ('produtos', '0012_alter_produto_vendedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrinho',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrinho',
            unique_together={('carrinho', 'produto')},
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='data_adicao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='preco_unitario',
        ),
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='total',
        ),
    ]
