# Generated by Django 5.1.7 on 2025-04-28 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_update_data_adicao_default'),
        ('vendedor', '0018_vendedor_justificativa_recusa'),
    ]

    operations = [
        # Removendo a operação que causa o erro
        # migrations.RemoveField(
        #     model_name='itemcarrinho',
        #     name='carrinho',
        # ),
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='produto',
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cnpj',
            field=models.CharField(max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cultivo_principal',
            field=models.CharField(choices=[('feijao', 'Feijão'), ('algodao', 'Algodão'), ('gergelim', 'Gergelim'), ('pastagem', 'Pastagem'), ('milho', 'Milho'), ('soja', 'Soja')], max_length=20, verbose_name='Cultivo Principal'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='endereco',
            field=models.CharField(max_length=200, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='hectares',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Hectares'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nome_propriedade',
            field=models.CharField(max_length=100, verbose_name='Nome da Propriedade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='referencia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Referência'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='core.usuario'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='vendedor.vendedor'),
        ),
        migrations.DeleteModel(
            name='Carrinho',
        ),
        migrations.DeleteModel(
            name='ItemCarrinho',
        ),
    ]
