# Generated by Django 5.1.7 on 2025-04-28 21:27

import produtos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('HERBICIDA', 'Herbicida'), ('INSETICIDA', 'Inseticida'), ('FUNGICIDA', 'Fungicida'), ('OLEO_MINERAL', 'Óleo Mineral'), ('SEMENTE', 'Semente')], max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('core_product_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID do Produto Core')),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('moeda', models.CharField(choices=[('BRL', 'Real (R$)'), ('USD', 'Dólar ($)'), ('EUR', 'Euro (€)')], default='BRL', max_length=3)),
                ('volume_disponivel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unidade_medida', models.CharField(choices=[('kg', 'Quilograma (kg)'), ('l', 'Litro (L)'), ('un', 'Unidade (un)')], default='un', max_length=2)),
                ('tipo', models.CharField(choices=[('soja', 'Soja'), ('milho', 'Milho'), ('pastagem', 'Pastagem'), ('sorgo', 'Sorgo')], default='soja', max_length=20)),
                ('embalagem', models.CharField(default='Saco', max_length=50)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('quantidade_minima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('peneira', models.CharField(blank=True, max_length=50, null=True)),
                ('variedade', models.CharField(blank=True, max_length=100, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=produtos.models.product_image_path)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_da_semente', models.CharField(blank=True, choices=[('branca', 'Semente Branca'), ('tratada', 'Semente Tratada')], max_length=20, null=True, verbose_name='Tipo da Semente')),
                ('tratamento_da_semente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tratamento da Semente')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
            },
        ),
    ]
