# Generated by Django 5.1.7 on 2025-04-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('soja', 'Soja'), ('milho', 'Milho'), ('pastagem', 'Pastagem'), ('sorgo', 'Sorgo'), ('algodao', 'Algodão'), ('feijao', 'Feijão'), ('gergelim', 'Gergelim'), ('girasol', 'Girasol'), ('milho_pipoca', 'Milho Pipoca'), ('arros', 'Arroz'), ('pecuaria', 'Pecuária')], default='soja', max_length=20),
        ),
    ]
