# Generated by Django 5.1.7 on 2025-04-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tratamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
