# Generated by Django 5.1.7 on 2025-04-03 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='vendedor.vendedor'),
        ),
    ]
