# Generated by Django 5.1.7 on 2025-04-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_tratamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('SEMENTES', 'Sementes'), ('FERTILIZANTES', 'Fertilizantes'), ('DEFENSIVOS', 'Defensivos'), ('MAQUINARIOS', 'Maquinários'), ('OUTROS', 'Outros')], max_length=100),
        ),
    ]
