# Generated by Django 5.1.7 on 2025-05-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('HERBICIDA', 'Herbicida'), ('INSETICIDA', 'Inseticida'), ('FUNGICIDA', 'Fungicida'), ('OLEO_MINERAL', 'Óleo Mineral'), ('SEMENTE', 'Semente'), ('NUTRICAO_VEGETAL', 'Nutrição Vegetal'), ('BIOLOGICO', 'Biológico')], max_length=100),
        ),
    ]
