# Generated by Django 5.1.7 on 2025-04-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('HERBICIDA', 'Herbicida'), ('INSETICIDA', 'Inseticida'), ('FUNGICIDA', 'Fungicida'), ('OLEO_MINERAL', 'Óleo mineral'), ('SEMENTE', 'Semente')], max_length=100),
        ),
    ]
