# Generated by Django 5.1.7 on 2025-04-06 16:34

import produtos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('SEMENTES', 'Sementes'), ('FERTILIZANTES', 'Fertilizantes'), ('DEFENSIVOS', 'Defensivos'), ('MAQUINARIOS', 'Maquinários'), ('OUTROS', 'Outros')], default='OUTROS', max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='embalagem',
            field=models.CharField(blank=True, choices=[('bag', 'Saco'), ('box', 'Caixa'), ('bottle', 'Garrafa'), ('can', 'Lata'), ('other', 'Outro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=produtos.models.product_image_path),
        ),
        migrations.AlterField(
            model_name='produto',
            name='lote',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='moeda',
            field=models.CharField(choices=[('BRL', 'Real (R$)'), ('USD', 'Dólar ($)'), ('EUR', 'Euro (€)')], default='BRL', max_length=3),
        ),
        migrations.AlterField(
            model_name='produto',
            name='peneira',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='permite_troca',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_minima',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('feijao', 'Feijão'), ('algodao', 'Algodão'), ('gergelim', 'Gergelim'), ('pastagem', 'Pastagem'), ('milho', 'Milho'), ('soja', 'Soja'), ('outros', 'Outros')], default='outros', max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('kg', 'Quilograma (kg)'), ('g', 'Grama (g)'), ('l', 'Litro (L)'), ('ml', 'Mililitro (mL)'), ('un', 'Unidade (un)')], default='un', max_length=2),
        ),
        migrations.AlterField(
            model_name='produto',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='volume_disponivel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
