# Generated by Django 5.1.7 on 2025-04-07 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_remove_produto_quantidade_produto_ativo_and_more'),
    ]

    operations = [
    ]
