# Generated by Django 5.1.7 on 2025-04-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo_da_semente',
            field=models.CharField(blank=True, choices=[('branca', 'Semente Branca'), ('tratada', 'Semente Tratada')], max_length=20, null=True, verbose_name='Tipo da Semente'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tratamento_da_semente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tratamento da Semente'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('HERBICIDA', 'Herbicida'), ('INSETICIDA', 'Inseticida'), ('FUNGICIDA', 'Fungicida'), ('OLEO_MINERAL', 'Óleo Mineral'), ('SEMENTE', 'Semente')], max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('soja', 'Soja'), ('milho', 'Milho'), ('pastagem', 'Pastagem'), ('sorgo', 'Sorgo')], default='soja', max_length=20),
        ),
    ]
