# Generated by Django 5.1.7 on 2025-04-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_alter_produto_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='permite_troca',
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('kg', 'Quilograma (kg)'), ('l', 'Litro (L)'), ('un', 'Unidade (un)')], default='un', max_length=2),
        ),
    ]
