# Generated by Django 5.1.7 on 2025-04-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_remove_produto_permite_troca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='embalagem',
            field=models.CharField(default='Saco', max_length=50),
        ),
    ]
