# Generated by Django 5.1.7 on 2025-04-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_alter_produto_embalagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='vendedor',
        ),
    ]
