# Generated by Django 5.1.7 on 2025-04-25 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_produto_vendedor'),
        ('vendedor', '0018_vendedor_justificativa_recusa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='vendedor.vendedor'),
        ),
    ]
