# Generated by Django 5.1.7 on 2025-04-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_alter_produto_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='produto',
            name='core_product_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID do Produto Core'),
        ),
    ]
