# Generated by Django 5.1.7 on 2025-04-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_remove_produto_vendedor_produto_core_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('HERBICIDA', 'Herbicida'), ('INSETICIDA', 'Inseticida'), ('FUNGICIDA', 'Fungicida'), ('OLEO_MINERAL', 'Óleo Mineral'), ('SEMENTE', 'Semente')], default='HERBICIDA', max_length=20),
        ),
    ]
