# Generated by Django 5.2 on 2025-04-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_remove_produto_vendedor_produto_core_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='core_product_id',
            field=models.PositiveIntegerField(null=True, blank=True, unique=True, verbose_name='ID do Produto Core'),
        ),
    ]
