# Generated by Django 5.1.7 on 2025-04-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_alter_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo_produto',
            field=models.CharField(choices=[('SOJA', 'Soja'), ('MILHO', 'Milho'), ('PASTAGEM', 'Pastagem'), ('SORGO', 'Sorgo')], default='SOJA', max_length=20),
        ),
    ]
