# Generated by Django 5.1.7 on 2025-04-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0015_produto_tipo_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tipo_produto',
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('soja', 'Soja'), ('milho', 'Milho'), ('pastagem', 'Pastagem'), ('sorgo', 'Sorgo')], default='soja', max_length=20),
        ),
    ]
