# Generated by Django 5.1.7 on 2025-04-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0016_remove_produto_tipo_produto_alter_produto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo_da_semente',
            field=models.CharField(blank=True, choices=[('branca', 'Semente Branca'), ('tratada', 'Semente Tratada')], max_length=20, null=True, verbose_name='Tipo da Semente'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tratamento_da_semente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tratamento da Semente'),
        ),
    ]
