# Generated by Django 5.1.7 on 2025-04-05 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
        ('vendedor', '0005_remove_vendedor_bairro_remove_vendedor_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='vendedor.vendedor'),
        ),
    ]
