# Generated by Django 5.1.7 on 2025-04-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='data_criacao',
            new_name='data_pedido',
        ),
    ]
