# Generated by Django 5.2 on 2025-04-30 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='hectares_atendidos',
            field=models.IntegerField(blank=True, help_text='Quantidade de hectares atendidos (entre 10 e 300)', null=True, validators=[django.core.validators.MinValueValidator(10, message='O valor mínimo é 10 hectares'), django.core.validators.MaxValueValidator(300, message='O valor máximo é 300 hectares')], verbose_name='Hectares Atendidos'),
        ),
    ]
