# Generated by Django 5.1.7 on 2025-04-07 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_cep_alter_usuario_cpf_and_more'),
    ]

    operations = [
    ]
