# Generated by Django 5.1.7 on 2025-04-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_sobrenome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='orgao_emissor',
        ),
    ]
