# Generated by Django 5.1.7 on 2025-04-28 17:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('culturas_atendidas', models.JSONField(blank=True, default=list, help_text='Lista de culturas atendidas pelo vendedor')),
                ('hectares_atendidos', models.IntegerField(default=10, help_text='Quantidade de hectares atendidos pelo vendedor (entre 10 e 300)', validators=[django.core.validators.MaxValueValidator(300, message='O máximo de hectares é 300')])),
                ('rg', models.FileField(blank=True, null=True, upload_to='documentos/rg/')),
                ('cnh', models.FileField(blank=True, null=True, upload_to='documentos/cnh/')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('status_aprovacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=10, verbose_name='Status de Aprovação')),
                ('justificativa_recusa', models.TextField(blank=True, null=True, verbose_name='Justificativa da Recusa')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['-created_at'],
            },
        ),
    ]
