# Generated by Django 5.1.7 on 2025-05-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='hectares_livres',
            field=models.IntegerField(help_text='Quantidade de hectares atendidos pelo vendedor'),
        ),
    ]
