# Generated by Django 5.1.7 on 2025-04-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='cnh',
            field=models.FileField(blank=True, null=True, upload_to='documentos/cnh/'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='hectares_atendidos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='rg',
            field=models.FileField(blank=True, null=True, upload_to='documentos/rg/'),
        ),
    ]
