# Generated by Django 5.2 on 2025-04-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='cnh_verso',
            field=models.FileField(blank=True, null=True, upload_to='documentos/cnh/'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='rg_verso',
            field=models.FileField(blank=True, null=True, upload_to='documentos/rg/'),
        ),
    ]
