# Generated by Django 5.1.7 on 2025-04-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0002_vendedor_cnh_vendedor_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='documento_cnpj',
            field=models.FileField(blank=True, null=True, upload_to='documentos/cnpj/', verbose_name='Documento CNPJ'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='documento_inscricao_estadual',
            field=models.FileField(blank=True, null=True, upload_to='documentos/ie/', verbose_name='Documento Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='documento_inscricao_municipal',
            field=models.FileField(blank=True, null=True, upload_to='documentos/im/', verbose_name='Documento Inscrição Municipal'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Gerais'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='observacoes_documentos',
            field=models.TextField(blank=True, null=True, verbose_name='Observações sobre Documentos'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='status_aprovacao',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=10, verbose_name='Status de Aprovação'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='cnh',
            field=models.FileField(blank=True, null=True, upload_to='documentos/cnh/', verbose_name='CNH'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='rg',
            field=models.FileField(blank=True, null=True, upload_to='documentos/rg/', verbose_name='RG'),
        ),
    ]
