# Generated by Django 5.1.7 on 2025-04-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0003_vendedor_data_aprovacao_vendedor_documento_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='cnh',
            field=models.FileField(blank=True, null=True, upload_to='documentos/cnh/'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='documento_cnpj',
            field=models.FileField(blank=True, null=True, upload_to='documentos/cnpj/'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='documento_inscricao_estadual',
            field=models.FileField(blank=True, null=True, upload_to='documentos/ie/'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='documento_inscricao_municipal',
            field=models.FileField(blank=True, null=True, upload_to='documentos/im/'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='observacoes_documentos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='rg',
            field=models.FileField(blank=True, null=True, upload_to='documentos/rg/'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='status_aprovacao',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
