# Generated by Django 5.1.7 on 2025-04-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0004_vendedor_bairro_alter_vendedor_cep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='data_aprovacao',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='documento_cnpj',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='documento_inscricao_estadual',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='documento_inscricao_municipal',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='inscricao_municipal',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='observacoes_documentos',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='status_aprovacao',
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
