# Generated by Django 5.1.7 on 2025-04-06 03:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0005_remove_vendedor_bairro_remove_vendedor_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='razao_social',
        ),
        migrations.AddField(
            model_name='vendedor',
            name='conquistas',
            field=models.JSONField(default=dict, help_text='Conquistas desbloqueadas'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='itens_inventario',
            field=models.JSONField(default=dict, help_text='Itens no inventário'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='missoes_completadas',
            field=models.IntegerField(default=0, help_text='Total de missões completadas'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='moedas',
            field=models.IntegerField(default=0, help_text='Moedas do jogo'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='nivel',
            field=models.IntegerField(default=1, help_text='Nível do vendedor no jogo'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='pontos_experiencia',
            field=models.IntegerField(default=0, help_text='Pontos de experiência acumulados'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='ranking',
            field=models.IntegerField(default=0, help_text='Posição no ranking'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='ultima_missao',
            field=models.DateTimeField(blank=True, help_text='Data da última missão completada', null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='hectares_atendidos',
            field=models.IntegerField(default=10, help_text='Quantidade de hectares atendidos pelo vendedor (entre 10 e 300)', validators=[django.core.validators.MinValueValidator(10, message='O mínimo de hectares é 10'), django.core.validators.MaxValueValidator(300, message='O máximo de hectares é 300')]),
        ),
    ]
