# Generated by Django 5.1.7 on 2025-04-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0005_remove_vendedor_bairro_remove_vendedor_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='hectares_atendidos',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Quantidade de hectares atendidos pelo vendedor', max_digits=10),
        ),
    ]
