# Generated by Django 5.1.7 on 2025-04-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0006_remove_vendedor_cnpj_remove_vendedor_razao_social_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='inscricao_estadual',
        ),
    ]
