# Generated by Django 5.1.7 on 2025-04-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0007_remove_vendedor_inscricao_estadual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='conquistas',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='itens_inventario',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='missoes_completadas',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='moedas',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='pontos_experiencia',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='ranking',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='ultima_missao',
        ),
    ]
