# Generated by Django 5.1.7 on 2025-04-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0007_alter_vendedor_hectares_atendidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='conquistas',
            field=models.JSONField(default=dict, help_text='Conquistas desbloqueadas'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='itens_inventario',
            field=models.JSONField(default=dict, help_text='Itens no inventário'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='missoes_completadas',
            field=models.IntegerField(default=0, help_text='Total de missões completadas'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='moedas',
            field=models.IntegerField(default=0, help_text='Moedas do jogo'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='nivel',
            field=models.IntegerField(default=1, help_text='Nível do vendedor no jogo'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='pontos_experiencia',
            field=models.IntegerField(default=0, help_text='Pontos de experiência acumulados'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='ranking',
            field=models.IntegerField(default=0, help_text='Posição no ranking'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='ultima_missao',
            field=models.DateTimeField(blank=True, help_text='Data da última missão completada', null=True),
        ),
    ]
