# Generated by Django 5.1.7 on 2025-04-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0008_vendedor_conquistas_vendedor_itens_inventario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
