# Generated by Django 5.1.7 on 2025-04-05 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0009_alter_vendedor_cep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='razao_social',
        ),
    ]
