# Generated by Django 5.1.7 on 2025-04-07 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0009_vendedor_data_aprovacao_alter_vendedor_usuario'),
    ]

    operations = [
    ]
