# Generated by Django 5.1.7 on 2025-04-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0012_alter_vendedor_cep_alter_vendedor_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='culturas_atendidas',
            field=models.CharField(blank=True, choices=[('soja', 'Soja'), ('milho', 'Milho'), ('algodao', 'Algodão'), ('feijao', 'Feijão'), ('gergelim', 'Gergelim'), ('girasol', 'Girasol'), ('pastagem', 'Pastagem'), ('milho_pipoca', 'Milho Pipoca'), ('arroz', 'Arroz'), ('pecuaria', 'Pecuária')], help_text='Culturas atendidas pelo vendedor (múltipla escolha)', max_length=200, null=True),
        ),
    ]
