# Generated by Django 5.1.7 on 2025-04-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0013_vendedor_culturas_atendidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='culturas_atendidas',
            field=models.JSONField(blank=True, default=list, help_text='Culturas atendidas pelo vendedor'),
        ),
    ]
