# Generated by Django 5.1.7 on 2025-04-12 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0014_alter_vendedor_culturas_atendidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='culturas_atendidas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de culturas atendidas pelo vendedor'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='hectares_atendidos',
            field=models.IntegerField(default=10, help_text='Quantidade de hectares atendidos pelo vendedor (entre 10 e 300)', validators=[django.core.validators.MaxValueValidator(300, message='O máximo de hectares é 300')]),
        ),
    ]
