# Generated by Django 5.1.7 on 2025-04-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0015_alter_vendedor_culturas_atendidas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
