# Generated by Django 5.1.7 on 2025-04-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0016_vendedor_bairro_vendedor_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='status_aprovacao',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=10, verbose_name='Status de Aprovação'),
        ),
    ]
