# Generated by Django 5.1.7 on 2025-04-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0017_vendedor_status_aprovacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='justificativa_recusa',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa da Recusa'),
        ),
    ]
