# Generated by Django 5.1.7 on 2025-04-02 17:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('vendedores', '0002_vendedor_cnpj_vendedor_inscricao_estadual_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['-created_at'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.RemoveField(
            model_name='produto',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('SEMENTES', 'Sementes'), ('FERTILIZANTES', 'Fertilizantes'), ('DEFENSIVOS', 'Defensivos'), ('MAQUINARIOS', 'Maquinários'), ('OUTROS', 'Outros')], default='OUTROS', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='produto',
            name='embalagem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='fabricante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='lote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='moeda',
            field=models.CharField(blank=True, choices=[('BRL', 'Real'), ('USD', 'Dólar')], default='BRL', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='peneira',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='permite_troca',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_minima',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('SOJA', 'Soja'), ('MILHO', 'Milho'), ('CAFE', 'Café'), ('OUTROS', 'Outros')], default='OUTROS', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(blank=True, choices=[('KG', 'Quilograma'), ('TON', 'Tonelada'), ('L', 'Litro'), ('ML', 'Mililitro'), ('UN', 'Unidade')], default='UN', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='validade',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='variedade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='vendedores.vendedor'),
        ),
        migrations.AddField(
            model_name='produto',
            name='volume_disponivel',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterModelTable(
            name='produto',
            table=None,
        ),
    ]
