# Generated by Django 5.1.7 on 2025-04-04 02:57

import django.core.validators
import produtos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_options_remove_produto_criado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_inicial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), produtos.models.validate_image_size, produtos.models.validate_image_dimensions]),
        ),
    ]
