# Generated by Django 5.1.7 on 2025-04-04 14:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_estoque_produto_estoque_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='validade',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
