# Generated by Django 5.1.7 on 2025-04-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produto_validade'),
    ]

    operations = [
    ]
