# Generated by Django 5.1.7 on 2025-04-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Municipal'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='razao_social',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Razão Social'),
        ),
    ]
