# Generated by Django 5.2 on 2025-04-16 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=3)),
                ('destino', models.CharField(max_length=3)),
                ('data_voo', models.DateField()),
                ('companhia', models.CharField(max_length=100)),
                ('milhas', models.PositiveIntegerField()),
                ('taxas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('economia_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
